server:
  applicationConnectors:
    - type: http
      port: 17000
  adminConnectors:
    - type: http
      port: 17001

elasticsearch:
  hosts:
  - ${ELASTICSEARCH_HOST}
  cluster: ${ELASTICSEARCH_CLUSTER_NAME}
  tableNamePrefix: ${ELASTICSEARCH_TABLE_NAME_PREFIX}
  port: ${ELASTICSEARCH_PORT}

hbase:
  secure : false
  tableName: ${HBASE_TABLE_NAME}
  hbaseZookeeperQuorum: ${HBASE_ZOOKEEPER_QUORUM}
  hbaseZookeeperClientPort: ${HBASE_ZOOKEEPER_CLIENT_PORT}

cluster:
  name: foxtrot
  discovery:
    type: ${DISCOVERY_TYPE}
    disableMulticast: true
    members: ["localhost:5701"]

cacheConfig:
  maxIdleSeconds: 15
  timeToLiveSeconds: 15

logging:
  level: INFO
  loggers:
    com.flipkart.foxtrot.core.querystore.actions: DEBUG
    org.apache.hadoop.hbase.zookeeper: WARN
    org.apache.zookeeper: WARN
    org.apache.hadoop.hbase.client: WARN
  appenders:
    - type: console
      threshold: TRACE
      timeZone: IST
      logFormat: "%(%-5level) [%date] %X{TRACE-ID} [%thread] [%logger{0}]: %message%n"

cardinality:
  enabled: true
  batchSize: 10
  active: true
  interval: 86400
  initialDelay: 6
  maxCardinality: 20000

deletionconfig:
  active: true
  interval: 86400
  initialdelay: 60

esIndexOptimizationConfig:
  active: true
  interval: 86400
  initialDelay: 6

consoleHistoryConfig:
  active: true
  interval: 86400
  initialDelay: 10

